wandb_version: 1

learning_rate:
  desc: null
  value: 2.0e-05
weight_decay:
  desc: null
  value: 0.01
num_train_epochs:
  desc: null
  value: 2
train_subsample_size:
  desc: null
  value: 1000
architecture:
  desc: null
  value: distilbert
dataset_name:
  desc: null
  value: rotten_tomatoes
model_name:
  desc: null
  value: distilbert-base-uncased
instance:
  desc: null
  value: ml.g4dn.2xlarge
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705075649.497657
    t:
      1:
      - 5
      - 11
      - 15
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 15
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.2
      6: 4.31.0
      8:
      - 1
      - 5
      13: linux-x86_64
