wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: log_loss
penalty:
  desc: null
  value: l1
architecture:
  desc: null
  value: SGDClassifier
dataset_name:
  desc: null
  value: rotten_tomatoes
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.2
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705060338.405625
    t:
      1:
      - 5
      - 49
      - 51
      - 53
      - 55
      2:
      - 5
      - 49
      - 51
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.16.2
      8:
      - 5
      10:
      - 5
      13: linux-x86_64
    viz:
      precision_recall:
        id: wandb/pr_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: precision_recall
